[package]
name = "hank"
version = "0.1.0"
edition = "2024"

[term]
color = "always"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
cliclack = "0.5.4"
console = "0.16.3"
dirs = "6.0.0"
regex = "1.12.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
strum = { version = "0.28.0", features = ["derive"] }
